### ISSUE TITLE
Flutter_onesgnal plugin deprecated migrate to android 2 on flutter pub get

### ISSUE THREAD

**Issue by yahi99** [piggyvault/piggyvault#183]
Flutter_onesgnal plugin deprecated migrate to android 2 on flutter pub get

**Comment by Abhith** [comment]
@yahi99 Thanks for reporting the issue. 
I started working on it and mentioned the blocked state in detail in this comment https://github.com/piggyvault/piggyvault/issues/186#issuecomment-1069249314 .
