### ISSUE TITLE
Bug IntroViews - Mobile

### ISSUE THREAD

**Issue by felipealbuquerq** [piggyvault/piggyvault#63]
in first access the loading not work, but when I did hot reload the slides is not show, because is not first access... then it works 🤔

Details:
https://youtu.be/clt3RAC99j4

**Comment by Abhith** [comment]
On the current build, during first access intro views shown as expected. But after login, a loading indicator keeps spinning on the dashboard.

And intro views not shown in case app reopened (working as expected), and no loading spinner issues too.

**Comment by felipealbuquerq** [comment]
@Abhith I don't create login page navigation, but I fix bug it.

**Comment by felipealbuquerq** [comment]
I didn't create the login page navigation, but I made the bug.
