### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by felipealbuquerq** [piggyvault/piggyvault#72]
![image](https://user-images.githubusercontent.com/1964926/69055070-b5c87800-09eb-11ea-99b6-e80b0a2031db.png)

Cannot read property 'getToken' of undefined https://piggyvault.in/swagger/v1/swagger.json

**Comment by Abhith** [comment]
The page opening fine here, is this after you tried something like tried to run any API call from swagger itself?

**Comment by felipealbuquerq** [comment]
![anonymous](https://user-images.githubusercontent.com/1964926/69058978-69813600-09f3-11ea-98c0-843aa82c243b.png)

Sorry, it's a false positive error...
